import type { Metadata } from 'next'
import { ReactNode } from 'react'

import { DashBoardLayout } from '../layout/dashboard'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function DashLayout({ children }: { children: ReactNode }) {
  return <DashBoardLayout>{children}</DashBoardLayout>
}
