import '../globals.css'

import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default async function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
      <Toaster />
    </>
  )
}
