import '../styles/globals.css'

import { Toaster } from '@/components/ui/toaster'
import { LoginLayoutComponent } from './layout/public'

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default async function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <LoginLayoutComponent>
        {children}
        <Toaster />
      </LoginLayoutComponent>
    </>
  )
}
